 spring:
  profiles: dev
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: root
    type: com.mchange.v2.c3p0.ComboPooledDataSource
    url: jdbc:mysql:///ntsp713db
    username: root
---

 spring:
  profiles: test
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: root
    type: org.apache.commons.dbcp2.BasicDataSource
    url: jdbc:mysql:///ntsp713db
    username: root
---   
 spring:   
  profiles: uat
  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    password: manager
    type: org.apache.commons.dbcp2.BasicDataSource
    url: jdbc:oracle:thin:@localhost:1521:xe
    username: system
---    
 spring:
  profiles: prod
  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    password: manager
    url: jdbc:oracle:thin:@localhost:1521:xe
    username: system
---   

spring: 
  profiles: 
    active: prod
