per:
  info:
    addrs: hyd
    id: 101
    job:
      company: HCL
      desg: Programmer
      salary: 67788.6
      skills:
      - java
      - spring
      - hibernate
    marks1:
    - 40
    - 50
    - 60
    marks2:
    - 50
    - 60
    - 70
    marks3:
    - 60
    - 70
    - 80
    name: rakesh
    phones:
      office: 8888888
      personal: 777777
      residence: 9999999
